# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/test/Gisement.ui'
#
# Created: Sun Sep 28 21:33:57 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Gisement(object):
    def setupUi(self, Gisement):
        Gisement.setObjectName(_fromUtf8("Gisement"))
        Gisement.resize(640, 480)
        self.verticalLayout = QtGui.QVBoxLayout(Gisement)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Gisement)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.groupBox.setSizeIncrement(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelCritere = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCritere.sizePolicy().hasHeightForWidth())
        self.labelCritere.setSizePolicy(sizePolicy)
        self.labelCritere.setObjectName(_fromUtf8("labelCritere"))
        self.horizontalLayout.addWidget(self.labelCritere)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setEditable(False)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tableWidgetActifs = QtGui.QTableWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetActifs.setFont(font)
        self.tableWidgetActifs.setMidLineWidth(0)
        self.tableWidgetActifs.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidgetActifs.setDragDropOverwriteMode(False)
        self.tableWidgetActifs.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetActifs.setAlternatingRowColors(True)
        self.tableWidgetActifs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetActifs.setShowGrid(False)
        self.tableWidgetActifs.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetActifs.setRowCount(0)
        self.tableWidgetActifs.setObjectName(_fromUtf8("tableWidgetActifs"))
        self.tableWidgetActifs.setColumnCount(15)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(14, item)
        self.tableWidgetActifs.horizontalHeader().setVisible(True)
        self.tableWidgetActifs.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetActifs.verticalHeader().setVisible(False)
        self.tableWidgetActifs.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetActifs.verticalHeader().setSortIndicatorShown(True)
        self.tableWidgetActifs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidgetActifs)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolButtonAdd = QtGui.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolButtonAdd.setFont(font)
        self.toolButtonAdd.setObjectName(_fromUtf8("toolButtonAdd"))
        self.horizontalLayout_2.addWidget(self.toolButtonAdd)
        self.toolButtonDelete = QtGui.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.toolButtonDelete.setFont(font)
        self.toolButtonDelete.setObjectName(_fromUtf8("toolButtonDelete"))
        self.horizontalLayout_2.addWidget(self.toolButtonDelete)
        self.toolButtonEdit = QtGui.QToolButton(self.groupBox)
        self.toolButtonEdit.setObjectName(_fromUtf8("toolButtonEdit"))
        self.horizontalLayout_2.addWidget(self.toolButtonEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Gisement)
        QtCore.QMetaObject.connectSlotsByName(Gisement)

    def retranslateUi(self, Gisement):
        Gisement.setWindowTitle(_translate("Gisement", "Form", None))
        self.groupBox.setTitle(_translate("Gisement", "Gisement d\'Actifs", None))
        self.label.setText(_translate("Gisement", "Valeur:", None))
        self.labelCritere.setText(_translate("Gisement", "Critère:", None))
        self.comboBox.setItemText(0, _translate("Gisement", "ISIN", None))
        self.comboBox.setItemText(1, _translate("Gisement", "NOM", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(0)
        item.setText(_translate("Gisement", "ISIN", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(1)
        item.setText(_translate("Gisement", "Nom", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(2)
        item.setText(_translate("Gisement", "Nominal", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(3)
        item.setText(_translate("Gisement", "Tx Facial", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(4)
        item.setText(_translate("Gisement", "Spread", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(5)
        item.setText(_translate("Gisement", "D Emission", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(6)
        item.setText(_translate("Gisement", "D Jouissance", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(7)
        item.setText(_translate("Gisement", "D Echéance", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(8)
        item.setText(_translate("Gisement", "Type", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(9)
        item.setText(_translate("Gisement", "Echue", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(10)
        item.setText(_translate("Gisement", "Forcee", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(11)
        item.setText(_translate("Gisement", "Prix", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(12)
        item.setText(_translate("Gisement", "Sensibilité", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(13)
        item.setText(_translate("Gisement", "Duration", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(14)
        item.setText(_translate("Gisement", "Tx Actuariel", None))
        self.toolButtonAdd.setText(_translate("Gisement", "+", None))
        self.toolButtonDelete.setText(_translate("Gisement", "-", None))
        self.toolButtonEdit.setText(_translate("Gisement", "E", None))
        self.pushButton.setText(_translate("Gisement", "Valider", None))

