# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/DPricer/presentation/Designer-Files/AddAssetDialog.ui'
#
# Created: Tue Oct  7 00:58:24 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_AddAsset(object):
    def setupUi(self, AddAsset):
        AddAsset.setObjectName(_fromUtf8("AddAsset"))
        AddAsset.resize(547, 557)
        self.verticalLayout = QtGui.QVBoxLayout(AddAsset)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 10, 5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBoxInfo = QtGui.QGroupBox(AddAsset)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxInfo.sizePolicy().hasHeightForWidth())
        self.groupBoxInfo.setSizePolicy(sizePolicy)
        self.groupBoxInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxInfo.setMaximumSize(QtCore.QSize(830, 16777215))
        self.groupBoxInfo.setObjectName(_fromUtf8("groupBoxInfo"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxInfo)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.iSINLabel = QtGui.QLabel(self.groupBoxInfo)
        self.iSINLabel.setObjectName(_fromUtf8("iSINLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.iSINLabel)
        self.isinLineEdit = QtGui.QLineEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isinLineEdit.sizePolicy().hasHeightForWidth())
        self.isinLineEdit.setSizePolicy(sizePolicy)
        self.isinLineEdit.setMaximumSize(QtCore.QSize(280, 16777215))
        self.isinLineEdit.setObjectName(_fromUtf8("isinLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.isinLineEdit)
        self.nomLabel = QtGui.QLabel(self.groupBoxInfo)
        self.nomLabel.setObjectName(_fromUtf8("nomLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.nomLabel)
        self.nomLineEdit = QtGui.QLineEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nomLineEdit.sizePolicy().hasHeightForWidth())
        self.nomLineEdit.setSizePolicy(sizePolicy)
        self.nomLineEdit.setMaximumSize(QtCore.QSize(280, 16777215))
        self.nomLineEdit.setObjectName(_fromUtf8("nomLineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.nomLineEdit)
        self.nominalLabel = QtGui.QLabel(self.groupBoxInfo)
        self.nominalLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.nominalLabel.setObjectName(_fromUtf8("nominalLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.nominalLabel)
        self.nominalLineEdit = QtGui.QLineEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nominalLineEdit.sizePolicy().hasHeightForWidth())
        self.nominalLineEdit.setSizePolicy(sizePolicy)
        self.nominalLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.nominalLineEdit.setMaximumSize(QtCore.QSize(280, 16777215))
        self.nominalLineEdit.setObjectName(_fromUtf8("nominalLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.nominalLineEdit)
        self.tauxFacialLabel = QtGui.QLabel(self.groupBoxInfo)
        self.tauxFacialLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.tauxFacialLabel.setObjectName(_fromUtf8("tauxFacialLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.tauxFacialLabel)
        self.doubleSpinBoxTauxFacial = QtGui.QDoubleSpinBox(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxTauxFacial.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxTauxFacial.setSizePolicy(sizePolicy)
        self.doubleSpinBoxTauxFacial.setMinimumSize(QtCore.QSize(102, 0))
        self.doubleSpinBoxTauxFacial.setMaximumSize(QtCore.QSize(180, 16777215))
        self.doubleSpinBoxTauxFacial.setProperty("value", 4.0)
        self.doubleSpinBoxTauxFacial.setObjectName(_fromUtf8("doubleSpinBoxTauxFacial"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxTauxFacial)
        self.labelSpread = QtGui.QLabel(self.groupBoxInfo)
        self.labelSpread.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelSpread.setObjectName(_fromUtf8("labelSpread"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelSpread)
        self.doubleSpinBoxSpread = QtGui.QDoubleSpinBox(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxSpread.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxSpread.setSizePolicy(sizePolicy)
        self.doubleSpinBoxSpread.setMinimumSize(QtCore.QSize(102, 0))
        self.doubleSpinBoxSpread.setMaximumSize(QtCore.QSize(180, 16777215))
        self.doubleSpinBoxSpread.setSingleStep(0.1)
        self.doubleSpinBoxSpread.setObjectName(_fromUtf8("doubleSpinBoxSpread"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxSpread)
        self.dateEmissionLabel = QtGui.QLabel(self.groupBoxInfo)
        self.dateEmissionLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.dateEmissionLabel.setObjectName(_fromUtf8("dateEmissionLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.dateEmissionLabel)
        self.dateEditDateEmission = QtGui.QDateEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditDateEmission.sizePolicy().hasHeightForWidth())
        self.dateEditDateEmission.setSizePolicy(sizePolicy)
        self.dateEditDateEmission.setMaximumSize(QtCore.QSize(180, 16777215))
        self.dateEditDateEmission.setWrapping(False)
        self.dateEditDateEmission.setFrame(True)
        self.dateEditDateEmission.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.dateEditDateEmission.setAccelerated(True)
        self.dateEditDateEmission.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.dateEditDateEmission.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateEmission.setDate(QtCore.QDate(2010, 6, 1))
        self.dateEditDateEmission.setCalendarPopup(True)
        self.dateEditDateEmission.setObjectName(_fromUtf8("dateEditDateEmission"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.dateEditDateEmission)
        self.dateDeJouissanceLabel = QtGui.QLabel(self.groupBoxInfo)
        self.dateDeJouissanceLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.dateDeJouissanceLabel.setObjectName(_fromUtf8("dateDeJouissanceLabel"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.dateDeJouissanceLabel)
        self.dateEditDateJouissance = QtGui.QDateEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditDateJouissance.sizePolicy().hasHeightForWidth())
        self.dateEditDateJouissance.setSizePolicy(sizePolicy)
        self.dateEditDateJouissance.setMaximumSize(QtCore.QSize(180, 16777215))
        self.dateEditDateJouissance.setAccelerated(True)
        self.dateEditDateJouissance.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateJouissance.setDate(QtCore.QDate(2010, 6, 1))
        self.dateEditDateJouissance.setCalendarPopup(True)
        self.dateEditDateJouissance.setObjectName(_fromUtf8("dateEditDateJouissance"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.dateEditDateJouissance)
        self.dateDChAnceLabel = QtGui.QLabel(self.groupBoxInfo)
        self.dateDChAnceLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.dateDChAnceLabel.setObjectName(_fromUtf8("dateDChAnceLabel"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.dateDChAnceLabel)
        self.dateEditDateEcheance = QtGui.QDateEdit(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEditDateEcheance.sizePolicy().hasHeightForWidth())
        self.dateEditDateEcheance.setSizePolicy(sizePolicy)
        self.dateEditDateEcheance.setMaximumSize(QtCore.QSize(180, 16777215))
        self.dateEditDateEcheance.setAccelerated(True)
        self.dateEditDateEcheance.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditDateEcheance.setDate(QtCore.QDate(2016, 6, 1))
        self.dateEditDateEcheance.setCalendarPopup(True)
        self.dateEditDateEcheance.setObjectName(_fromUtf8("dateEditDateEcheance"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.dateEditDateEcheance)
        self.typeLabel = QtGui.QLabel(self.groupBoxInfo)
        self.typeLabel.setObjectName(_fromUtf8("typeLabel"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = QtGui.QComboBox(self.groupBoxInfo)
        self.typeComboBox.setMaximumSize(QtCore.QSize(180, 110))
        self.typeComboBox.setObjectName(_fromUtf8("typeComboBox"))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.typeComboBox.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.typeComboBox)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(self.groupBoxInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(11730, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout.addWidget(self.groupBoxInfo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelSpread.setBuddy(self.doubleSpinBoxSpread)

        self.retranslateUi(AddAsset)
        QtCore.QMetaObject.connectSlotsByName(AddAsset)

    def retranslateUi(self, AddAsset):
        AddAsset.setWindowTitle(_translate("AddAsset", "Ajouter actif", None))
        self.groupBoxInfo.setTitle(_translate("AddAsset", "Fournir les informations nécessaires", None))
        self.iSINLabel.setText(_translate("AddAsset", "ISIN", None))
        self.nomLabel.setText(_translate("AddAsset", "Nom", None))
        self.nominalLabel.setText(_translate("AddAsset", "Nominal", None))
        self.tauxFacialLabel.setText(_translate("AddAsset", "Taux Facial", None))
        self.doubleSpinBoxTauxFacial.setSuffix(_translate("AddAsset", " %", None))
        self.labelSpread.setText(_translate("AddAsset", "Spread", None))
        self.doubleSpinBoxSpread.setSuffix(_translate("AddAsset", " %", None))
        self.dateEmissionLabel.setText(_translate("AddAsset", "Date Emission", None))
        self.dateEditDateEmission.setDisplayFormat(_translate("AddAsset", "dd/MM/yyyy", None))
        self.dateDeJouissanceLabel.setText(_translate("AddAsset", "Date de Jouissance", None))
        self.dateEditDateJouissance.setDisplayFormat(_translate("AddAsset", "dd/MM/yyyy", None))
        self.dateDChAnceLabel.setText(_translate("AddAsset", "Date d\'echeance", None))
        self.dateEditDateEcheance.setDisplayFormat(_translate("AddAsset", "dd/MM/yyyy", None))
        self.typeLabel.setText(_translate("AddAsset", "Type", None))
        self.typeComboBox.setItemText(0, _translate("AddAsset", "Normale ou Atypique (N)", None))
        self.typeComboBox.setItemText(1, _translate("AddAsset", "Amortissable (AMC)", None))
        self.typeComboBox.setItemText(2, _translate("AddAsset", "Revisable (REV)", None))
        self.typeComboBox.setItemText(3, _translate("AddAsset", "Amortissable Révisable (AMCREV)", None))

