# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/DPricer/presentation/Designer-Files/GererPortefeuilles.ui'
#
# Created: Wed Oct  8 16:57:11 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GererPortefeuilles(object):
    def setupUi(self, GererPortefeuilles):
        GererPortefeuilles.setObjectName(_fromUtf8("GererPortefeuilles"))
        GererPortefeuilles.resize(679, 536)
        self.verticalLayout = QtGui.QVBoxLayout(GererPortefeuilles)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBoxGisement = QtGui.QGroupBox(GererPortefeuilles)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxGisement.setFont(font)
        self.groupBoxGisement.setFlat(True)
        self.groupBoxGisement.setObjectName(_fromUtf8("groupBoxGisement"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxGisement)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(8, 15, 8, 5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetGisementPortefeuille = QtGui.QTableWidget(self.groupBoxGisement)
        self.tableWidgetGisementPortefeuille.setEditTriggers(QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidgetGisementPortefeuille.setAlternatingRowColors(True)
        self.tableWidgetGisementPortefeuille.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetGisementPortefeuille.setObjectName(_fromUtf8("tableWidgetGisementPortefeuille"))
        self.tableWidgetGisementPortefeuille.setColumnCount(2)
        self.tableWidgetGisementPortefeuille.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGisementPortefeuille.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetGisementPortefeuille.setHorizontalHeaderItem(1, item)
        self.tableWidgetGisementPortefeuille.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidgetGisementPortefeuille)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolButtonAdd = QtGui.QToolButton(self.groupBoxGisement)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.toolButtonAdd.setFont(font)
        self.toolButtonAdd.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonAdd.setObjectName(_fromUtf8("toolButtonAdd"))
        self.horizontalLayout.addWidget(self.toolButtonAdd)
        self.toolButtonRemove = QtGui.QToolButton(self.groupBoxGisement)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.toolButtonRemove.setFont(font)
        self.toolButtonRemove.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonRemove.setObjectName(_fromUtf8("toolButtonRemove"))
        self.horizontalLayout.addWidget(self.toolButtonRemove)
        self.toolButtonEdit = QtGui.QToolButton(self.groupBoxGisement)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButtonEdit.setFont(font)
        self.toolButtonEdit.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonEdit.setObjectName(_fromUtf8("toolButtonEdit"))
        self.horizontalLayout.addWidget(self.toolButtonEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.groupBoxGisement)
        self.lineWest = QtGui.QFrame(GererPortefeuilles)
        self.lineWest.setFrameShape(QtGui.QFrame.VLine)
        self.lineWest.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineWest.setObjectName(_fromUtf8("lineWest"))
        self.horizontalLayout_2.addWidget(self.lineWest)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(8, -1, 5, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.toolButtonAddToMyPortfolio = QtGui.QToolButton(GererPortefeuilles)
        self.toolButtonAddToMyPortfolio.setText(_fromUtf8(""))
        self.toolButtonAddToMyPortfolio.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonAddToMyPortfolio.setArrowType(QtCore.Qt.RightArrow)
        self.toolButtonAddToMyPortfolio.setObjectName(_fromUtf8("toolButtonAddToMyPortfolio"))
        self.verticalLayout_3.addWidget(self.toolButtonAddToMyPortfolio)
        self.toolButtonRemoveFromMyPortfolio = QtGui.QToolButton(GererPortefeuilles)
        self.toolButtonRemoveFromMyPortfolio.setText(_fromUtf8(""))
        self.toolButtonRemoveFromMyPortfolio.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonRemoveFromMyPortfolio.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButtonRemoveFromMyPortfolio.setObjectName(_fromUtf8("toolButtonRemoveFromMyPortfolio"))
        self.verticalLayout_3.addWidget(self.toolButtonRemoveFromMyPortfolio)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.lineEast = QtGui.QFrame(GererPortefeuilles)
        self.lineEast.setFrameShape(QtGui.QFrame.VLine)
        self.lineEast.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineEast.setObjectName(_fromUtf8("lineEast"))
        self.horizontalLayout_2.addWidget(self.lineEast)
        self.groupBoxMyPortfolios = QtGui.QGroupBox(GererPortefeuilles)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBoxMyPortfolios.setFont(font)
        self.groupBoxMyPortfolios.setObjectName(_fromUtf8("groupBoxMyPortfolios"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxMyPortfolios)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(8, 15, 8, 5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidgetPortefeuilles = QtGui.QTableWidget(self.groupBoxMyPortfolios)
        self.tableWidgetPortefeuilles.setAlternatingRowColors(True)
        self.tableWidgetPortefeuilles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetPortefeuilles.setObjectName(_fromUtf8("tableWidgetPortefeuilles"))
        self.tableWidgetPortefeuilles.setColumnCount(2)
        self.tableWidgetPortefeuilles.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetPortefeuilles.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetPortefeuilles.setHorizontalHeaderItem(1, item)
        self.tableWidgetPortefeuilles.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tableWidgetPortefeuilles)
        self.horizontalLayout_2.addWidget(self.groupBoxMyPortfolios)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(GererPortefeuilles)
        QtCore.QMetaObject.connectSlotsByName(GererPortefeuilles)

    def retranslateUi(self, GererPortefeuilles):
        GererPortefeuilles.setWindowTitle(_translate("GererPortefeuilles", "Gérer les Portefeuilles", None))
        self.groupBoxGisement.setTitle(_translate("GererPortefeuilles", "Gisement de portefeuilles", None))
        item = self.tableWidgetGisementPortefeuille.horizontalHeaderItem(0)
        item.setText(_translate("GererPortefeuilles", "isin", None))
        item = self.tableWidgetGisementPortefeuille.horizontalHeaderItem(1)
        item.setText(_translate("GererPortefeuilles", "Nom", None))
        self.toolButtonAdd.setText(_translate("GererPortefeuilles", "+", None))
        self.toolButtonRemove.setText(_translate("GererPortefeuilles", "-", None))
        self.toolButtonEdit.setText(_translate("GererPortefeuilles", "modif", None))
        self.groupBoxMyPortfolios.setTitle(_translate("GererPortefeuilles", "Mes Portefeuilles", None))
        item = self.tableWidgetPortefeuilles.horizontalHeaderItem(0)
        item.setText(_translate("GererPortefeuilles", "isin", None))
        item = self.tableWidgetPortefeuilles.horizontalHeaderItem(1)
        item.setText(_translate("GererPortefeuilles", "Nom", None))

