# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/DPricer/presentation/Designer-Files/MDI.ui'
#
# Created: Wed Oct  8 15:01:03 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MDIApp(object):
    def setupUi(self, MDIApp):
        MDIApp.setObjectName(_fromUtf8("MDIApp"))
        MDIApp.resize(660, 480)
        MDIApp.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MDIApp)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelUser = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Garamond"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelUser.setFont(font)
        self.labelUser.setFrameShape(QtGui.QFrame.WinPanel)
        self.labelUser.setFrameShadow(QtGui.QFrame.Raised)
        self.labelUser.setLineWidth(0)
        self.labelUser.setObjectName(_fromUtf8("labelUser"))
        self.horizontalLayout.addWidget(self.labelUser)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelDates = QtGui.QLabel(self.centralwidget)
        self.labelDates.setObjectName(_fromUtf8("labelDates"))
        self.horizontalLayout.addWidget(self.labelDates)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mdiArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mdiArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setViewMode(QtGui.QMdiArea.TabbedView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabShape(QtGui.QTabWidget.Rounded)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.verticalLayout.addWidget(self.mdiArea)
        MDIApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MDIApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 25))
        self.menubar.setMinimumSize(QtCore.QSize(0, 25))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPortefeuille = QtGui.QMenu(self.menubar)
        self.menuPortefeuille.setObjectName(_fromUtf8("menuPortefeuille"))
        self.menuParametres = QtGui.QMenu(self.menubar)
        self.menuParametres.setObjectName(_fromUtf8("menuParametres"))
        self.menuDispositionDesFenetres = QtGui.QMenu(self.menuParametres)
        self.menuDispositionDesFenetres.setObjectName(_fromUtf8("menuDispositionDesFenetres"))
        self.menuExtras = QtGui.QMenu(self.menubar)
        self.menuExtras.setObjectName(_fromUtf8("menuExtras"))
        self.menuBDD = QtGui.QMenu(self.menubar)
        self.menuBDD.setObjectName(_fromUtf8("menuBDD"))
        self.menuImporter = QtGui.QMenu(self.menuBDD)
        self.menuImporter.setObjectName(_fromUtf8("menuImporter"))
        self.menuCourbe = QtGui.QMenu(self.menubar)
        self.menuCourbe.setObjectName(_fromUtf8("menuCourbe"))
        self.menuImporterCourbe = QtGui.QMenu(self.menuCourbe)
        self.menuImporterCourbe.setObjectName(_fromUtf8("menuImporterCourbe"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MDIApp.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MDIApp)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusbar.setFont(font)
        self.statusbar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.statusbar.setAcceptDrops(False)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MDIApp.setStatusBar(self.statusbar)
        self.actionNW = QtGui.QAction(MDIApp)
        self.actionNW.setObjectName(_fromUtf8("actionNW"))
        self.actionAffiche = QtGui.QAction(MDIApp)
        self.actionAffiche.setObjectName(_fromUtf8("actionAffiche"))
        self.actionNouvelle_Fenetre = QtGui.QAction(MDIApp)
        self.actionNouvelle_Fenetre.setObjectName(_fromUtf8("actionNouvelle_Fenetre"))
        self.actionCalculette = QtGui.QAction(MDIApp)
        self.actionCalculette.setObjectName(_fromUtf8("actionCalculette"))
        self.actionProfilUtilisateur = QtGui.QAction(MDIApp)
        self.actionProfilUtilisateur.setObjectName(_fromUtf8("actionProfilUtilisateur"))
        self.actionMon_Portefeuille = QtGui.QAction(MDIApp)
        self.actionMon_Portefeuille.setObjectName(_fromUtf8("actionMon_Portefeuille"))
        self.actionCSV = QtGui.QAction(MDIApp)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionExcel = QtGui.QAction(MDIApp)
        self.actionExcel.setObjectName(_fromUtf8("actionExcel"))
        self.actionCSV_2 = QtGui.QAction(MDIApp)
        self.actionCSV_2.setObjectName(_fromUtf8("actionCSV_2"))
        self.actionExcel_2 = QtGui.QAction(MDIApp)
        self.actionExcel_2.setObjectName(_fromUtf8("actionExcel_2"))
        self.actionG_n_rer_Template_Excel = QtGui.QAction(MDIApp)
        self.actionG_n_rer_Template_Excel.setObjectName(_fromUtf8("actionG_n_rer_Template_Excel"))
        self.actionMettreAJour = QtGui.QAction(MDIApp)
        self.actionMettreAJour.setObjectName(_fromUtf8("actionMettreAJour"))
        self.actionCSVCourbe = QtGui.QAction(MDIApp)
        self.actionCSVCourbe.setObjectName(_fromUtf8("actionCSVCourbe"))
        self.actionExcelCourbe = QtGui.QAction(MDIApp)
        self.actionExcelCourbe.setObjectName(_fromUtf8("actionExcelCourbe"))
        self.actionGisement = QtGui.QAction(MDIApp)
        self.actionGisement.setObjectName(_fromUtf8("actionGisement"))
        self.actionAjoutObligation = QtGui.QAction(MDIApp)
        self.actionAjoutObligation.setObjectName(_fromUtf8("actionAjoutObligation"))
        self.actionMonPortefeuille = QtGui.QAction(MDIApp)
        self.actionMonPortefeuille.setObjectName(_fromUtf8("actionMonPortefeuille"))
        self.actionGererPortefeuille = QtGui.QAction(MDIApp)
        self.actionGererPortefeuille.setObjectName(_fromUtf8("actionGererPortefeuille"))
        self.actionImporterActifExcel = QtGui.QAction(MDIApp)
        self.actionImporterActifExcel.setObjectName(_fromUtf8("actionImporterActifExcel"))
        self.actionImporterActifCSV = QtGui.QAction(MDIApp)
        self.actionImporterActifCSV.setObjectName(_fromUtf8("actionImporterActifCSV"))
        self.actionAlertes = QtGui.QAction(MDIApp)
        self.actionAlertes.setObjectName(_fromUtf8("actionAlertes"))
        self.actionAutre = QtGui.QAction(MDIApp)
        self.actionAutre.setObjectName(_fromUtf8("actionAutre"))
        self.actionGenererFichierImport = QtGui.QAction(MDIApp)
        self.actionGenererFichierImport.setObjectName(_fromUtf8("actionGenererFichierImport"))
        self.actionVisualiser = QtGui.QAction(MDIApp)
        self.actionVisualiser.setObjectName(_fromUtf8("actionVisualiser"))
        self.actionGeneral = QtGui.QAction(MDIApp)
        self.actionGeneral.setObjectName(_fromUtf8("actionGeneral"))
        self.actionOnglets = QtGui.QAction(MDIApp)
        self.actionOnglets.setObjectName(_fromUtf8("actionOnglets"))
        self.actionSousFenetres = QtGui.QAction(MDIApp)
        self.actionSousFenetres.setObjectName(_fromUtf8("actionSousFenetres"))
        self.actionSimulateur = QtGui.QAction(MDIApp)
        self.actionSimulateur.setObjectName(_fromUtf8("actionSimulateur"))
        self.actionModifierMesPortefeuilles = QtGui.QAction(MDIApp)
        self.actionModifierMesPortefeuilles.setObjectName(_fromUtf8("actionModifierMesPortefeuilles"))
        self.menuPortefeuille.addAction(self.actionMonPortefeuille)
        self.menuPortefeuille.addAction(self.actionGererPortefeuille)
        self.menuPortefeuille.addSeparator()
        self.menuPortefeuille.addAction(self.actionModifierMesPortefeuilles)
        self.menuDispositionDesFenetres.addAction(self.actionOnglets)
        self.menuDispositionDesFenetres.addAction(self.actionSousFenetres)
        self.menuParametres.addAction(self.actionGeneral)
        self.menuParametres.addAction(self.menuDispositionDesFenetres.menuAction())
        self.menuExtras.addAction(self.actionCalculette)
        self.menuExtras.addAction(self.actionSimulateur)
        self.menuImporter.addAction(self.actionImporterActifExcel)
        self.menuImporter.addSeparator()
        self.menuImporter.addAction(self.actionGenererFichierImport)
        self.menuBDD.addAction(self.actionAjoutObligation)
        self.menuBDD.addSeparator()
        self.menuBDD.addAction(self.actionGisement)
        self.menuBDD.addSeparator()
        self.menuBDD.addAction(self.menuImporter.menuAction())
        self.menuImporterCourbe.addAction(self.actionExcelCourbe)
        self.menuCourbe.addAction(self.actionMettreAJour)
        self.menuCourbe.addAction(self.menuImporterCourbe.menuAction())
        self.menuCourbe.addSeparator()
        self.menuCourbe.addAction(self.actionVisualiser)
        self.menubar.addAction(self.menuPortefeuille.menuAction())
        self.menubar.addAction(self.menuBDD.menuAction())
        self.menubar.addAction(self.menuCourbe.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuParametres.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MDIApp)
        QtCore.QMetaObject.connectSlotsByName(MDIApp)

    def retranslateUi(self, MDIApp):
        MDIApp.setWindowTitle(_translate("MDIApp", "MainWindow", None))
        self.labelUser.setText(_translate("MDIApp", "TextLabel", None))
        self.labelDates.setText(_translate("MDIApp", "TextLabel", None))
        self.menuPortefeuille.setTitle(_translate("MDIApp", "Portefeuille", None))
        self.menuParametres.setTitle(_translate("MDIApp", "Paramètres", None))
        self.menuDispositionDesFenetres.setTitle(_translate("MDIApp", "Disposition des fenêtres", None))
        self.menuExtras.setTitle(_translate("MDIApp", "Extras", None))
        self.menuBDD.setTitle(_translate("MDIApp", "Actifs", None))
        self.menuImporter.setTitle(_translate("MDIApp", "Importer", None))
        self.menuCourbe.setTitle(_translate("MDIApp", "Courbe Taux", None))
        self.menuImporterCourbe.setTitle(_translate("MDIApp", "Importer", None))
        self.menuAbout.setTitle(_translate("MDIApp", "About", None))
        self.actionNW.setText(_translate("MDIApp", "Ouvrir écheancier", None))
        self.actionAffiche.setText(_translate("MDIApp", "affiche", None))
        self.actionNouvelle_Fenetre.setText(_translate("MDIApp", "Nouvelle Fenetre", None))
        self.actionCalculette.setText(_translate("MDIApp", "Calculette", None))
        self.actionProfilUtilisateur.setText(_translate("MDIApp", "Profil Utilisateur", None))
        self.actionMon_Portefeuille.setText(_translate("MDIApp", "Mes Portefeuilles", None))
        self.actionCSV.setText(_translate("MDIApp", "CSV", None))
        self.actionExcel.setText(_translate("MDIApp", "Excel", None))
        self.actionCSV_2.setText(_translate("MDIApp", "CSV", None))
        self.actionExcel_2.setText(_translate("MDIApp", "Excel", None))
        self.actionG_n_rer_Template_Excel.setText(_translate("MDIApp", "Générer Template Excel", None))
        self.actionMettreAJour.setText(_translate("MDIApp", "&Mettre à jour", None))
        self.actionCSVCourbe.setText(_translate("MDIApp", "CSV", None))
        self.actionExcelCourbe.setText(_translate("MDIApp", "Excel", None))
        self.actionGisement.setText(_translate("MDIApp", "Gisement", None))
        self.actionAjoutObligation.setText(_translate("MDIApp", "Ajouter actif", None))
        self.actionMonPortefeuille.setText(_translate("MDIApp", "Mes Portefeuilles", None))
        self.actionGererPortefeuille.setText(_translate("MDIApp", "Gérer Portefeuilles", None))
        self.actionImporterActifExcel.setText(_translate("MDIApp", "Excel", None))
        self.actionImporterActifCSV.setText(_translate("MDIApp", "CSV", None))
        self.actionAlertes.setText(_translate("MDIApp", "Alertes", None))
        self.actionAutre.setText(_translate("MDIApp", "Autres", None))
        self.actionGenererFichierImport.setText(_translate("MDIApp", "Générer fichier d\'import", None))
        self.actionVisualiser.setText(_translate("MDIApp", "&Visualiser", None))
        self.actionGeneral.setText(_translate("MDIApp", "General", None))
        self.actionOnglets.setText(_translate("MDIApp", "Onglets", None))
        self.actionSousFenetres.setText(_translate("MDIApp", "Fenêtres", None))
        self.actionSimulateur.setText(_translate("MDIApp", "Simulateur", None))
        self.actionModifierMesPortefeuilles.setText(_translate("MDIApp", "Modifier la structure de mes Portefeuilles", None))

