# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/DPricer/presentation/Designer-Files/Simulation.ui'
#
# Created: Sat Oct  4 19:02:12 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Simulation(object):
    def setupUi(self, Simulation):
        Simulation.setObjectName(_fromUtf8("Simulation"))
        Simulation.resize(640, 480)
        Simulation.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Simulation)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Simulation)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableWidgetActifs = QtGui.QTableWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetActifs.setFont(font)
        self.tableWidgetActifs.setMidLineWidth(0)
        self.tableWidgetActifs.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetActifs.setTabKeyNavigation(False)
        self.tableWidgetActifs.setProperty("showDropIndicator", False)
        self.tableWidgetActifs.setDragDropOverwriteMode(False)
        self.tableWidgetActifs.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetActifs.setAlternatingRowColors(True)
        self.tableWidgetActifs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetActifs.setShowGrid(False)
        self.tableWidgetActifs.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetActifs.setRowCount(0)
        self.tableWidgetActifs.setObjectName(_fromUtf8("tableWidgetActifs"))
        self.tableWidgetActifs.setColumnCount(9)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifs.setHorizontalHeaderItem(8, item)
        self.tableWidgetActifs.horizontalHeader().setVisible(True)
        self.tableWidgetActifs.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetActifs.verticalHeader().setVisible(False)
        self.tableWidgetActifs.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetActifs.verticalHeader().setSortIndicatorShown(True)
        self.tableWidgetActifs.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.tableWidgetActifs)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.addToSimulate = QtGui.QToolButton(Simulation)
        self.addToSimulate.setObjectName(_fromUtf8("addToSimulate"))
        self.verticalLayout.addWidget(self.addToSimulate)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.removeFromSimulate = QtGui.QToolButton(Simulation)
        self.removeFromSimulate.setObjectName(_fromUtf8("removeFromSimulate"))
        self.verticalLayout.addWidget(self.removeFromSimulate)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.groupBoxSimulate = QtGui.QGroupBox(Simulation)
        self.groupBoxSimulate.setObjectName(_fromUtf8("groupBoxSimulate"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxSimulate)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidgetActifsSimulation = QtGui.QTableWidget(self.groupBoxSimulate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetActifsSimulation.setFont(font)
        self.tableWidgetActifsSimulation.setMidLineWidth(0)
        self.tableWidgetActifsSimulation.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetActifsSimulation.setTabKeyNavigation(False)
        self.tableWidgetActifsSimulation.setProperty("showDropIndicator", False)
        self.tableWidgetActifsSimulation.setDragDropOverwriteMode(False)
        self.tableWidgetActifsSimulation.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetActifsSimulation.setAlternatingRowColors(True)
        self.tableWidgetActifsSimulation.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetActifsSimulation.setShowGrid(False)
        self.tableWidgetActifsSimulation.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetActifsSimulation.setRowCount(0)
        self.tableWidgetActifsSimulation.setObjectName(_fromUtf8("tableWidgetActifsSimulation"))
        self.tableWidgetActifsSimulation.setColumnCount(8)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetActifsSimulation.setHorizontalHeaderItem(7, item)
        self.tableWidgetActifsSimulation.horizontalHeader().setVisible(True)
        self.tableWidgetActifsSimulation.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetActifsSimulation.verticalHeader().setVisible(False)
        self.tableWidgetActifsSimulation.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetActifsSimulation.verticalHeader().setSortIndicatorShown(True)
        self.tableWidgetActifsSimulation.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tableWidgetActifsSimulation)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.groupBoxSimulate)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBoxSimulate)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setMinimum(-10.0)
        self.doubleSpinBox.setMaximum(15.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.groupBoxSimulate, 1, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButtonFermer = QtGui.QPushButton(Simulation)
        self.pushButtonFermer.setObjectName(_fromUtf8("pushButtonFermer"))
        self.horizontalLayout.addWidget(self.pushButtonFermer)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Simulation)
        QtCore.QMetaObject.connectSlotsByName(Simulation)

    def retranslateUi(self, Simulation):
        Simulation.setWindowTitle(_translate("Simulation", "Simulation", None))
        self.groupBox.setTitle(_translate("Simulation", "Actifs disponibles", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(0)
        item.setText(_translate("Simulation", "ISIN", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(1)
        item.setText(_translate("Simulation", "Nom", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(2)
        item.setText(_translate("Simulation", "Nominal", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(3)
        item.setText(_translate("Simulation", "Tx Facial", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(4)
        item.setText(_translate("Simulation", "Spread", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(5)
        item.setText(_translate("Simulation", "D Emission", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(6)
        item.setText(_translate("Simulation", "D Jouissance", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(7)
        item.setText(_translate("Simulation", "D Echéance", None))
        item = self.tableWidgetActifs.horizontalHeaderItem(8)
        item.setText(_translate("Simulation", "Tx Actuariel", None))
        self.addToSimulate.setText(_translate("Simulation", ">", None))
        self.removeFromSimulate.setText(_translate("Simulation", "<", None))
        self.groupBoxSimulate.setTitle(_translate("Simulation", "Actifs à simuler", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(0)
        item.setText(_translate("Simulation", "ISIN", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(1)
        item.setText(_translate("Simulation", "Nominal", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(2)
        item.setText(_translate("Simulation", "Tx Facial", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(3)
        item.setText(_translate("Simulation", "Spread", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(4)
        item.setText(_translate("Simulation", "Tx Actuariel", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(5)
        item.setText(_translate("Simulation", "Prix", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(6)
        item.setText(_translate("Simulation", "Nv Prix", None))
        item = self.tableWidgetActifsSimulation.horizontalHeaderItem(7)
        item.setText(_translate("Simulation", "Var prix (MAD)", None))
        self.label.setText(_translate("Simulation", "Varier le taux (shift)", None))
        self.doubleSpinBox.setSuffix(_translate("Simulation", " %", None))
        self.pushButtonFermer.setText(_translate("Simulation", "Fermer", None))

