# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/DPricer/DPricer/presentation/Designer-Files/StructurePortefeuille.ui'
#
# Created: Thu Oct  9 16:45:48 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StructurePortefeuille(object):
    def setupUi(self, StructurePortefeuille):
        StructurePortefeuille.setObjectName(_fromUtf8("StructurePortefeuille"))
        StructurePortefeuille.resize(863, 552)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StructurePortefeuille.sizePolicy().hasHeightForWidth())
        StructurePortefeuille.setSizePolicy(sizePolicy)
        StructurePortefeuille.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.verticalLayout = QtGui.QVBoxLayout(StructurePortefeuille)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setContentsMargins(-1, 8, 20, 8)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sLectionnerLePortefeuilleModifierLabel = QtGui.QLabel(StructurePortefeuille)
        self.sLectionnerLePortefeuilleModifierLabel.setWordWrap(False)
        self.sLectionnerLePortefeuilleModifierLabel.setObjectName(_fromUtf8("sLectionnerLePortefeuilleModifierLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sLectionnerLePortefeuilleModifierLabel)
        self.comboBoxSelect = QtGui.QComboBox(StructurePortefeuille)
        self.comboBoxSelect.setAutoFillBackground(False)
        self.comboBoxSelect.setEditable(True)
        self.comboBoxSelect.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBoxSelect.setFrame(True)
        self.comboBoxSelect.setObjectName(_fromUtf8("comboBoxSelect"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxSelect)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(StructurePortefeuille)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(180, 0))
        self.frame.setMaximumSize(QtCore.QSize(777777, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(6, -1, 4, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.toolButtonAddToMyPortfolio = QtGui.QToolButton(StructurePortefeuille)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonAddToMyPortfolio.sizePolicy().hasHeightForWidth())
        self.toolButtonAddToMyPortfolio.setSizePolicy(sizePolicy)
        self.toolButtonAddToMyPortfolio.setMaximumSize(QtCore.QSize(35, 16777215))
        self.toolButtonAddToMyPortfolio.setText(_fromUtf8(""))
        self.toolButtonAddToMyPortfolio.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonAddToMyPortfolio.setArrowType(QtCore.Qt.RightArrow)
        self.toolButtonAddToMyPortfolio.setObjectName(_fromUtf8("toolButtonAddToMyPortfolio"))
        self.verticalLayout_5.addWidget(self.toolButtonAddToMyPortfolio)
        self.toolButtonRemoveFromMyPortfolio = QtGui.QToolButton(StructurePortefeuille)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRemoveFromMyPortfolio.sizePolicy().hasHeightForWidth())
        self.toolButtonRemoveFromMyPortfolio.setSizePolicy(sizePolicy)
        self.toolButtonRemoveFromMyPortfolio.setMaximumSize(QtCore.QSize(35, 16777215))
        self.toolButtonRemoveFromMyPortfolio.setText(_fromUtf8(""))
        self.toolButtonRemoveFromMyPortfolio.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButtonRemoveFromMyPortfolio.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButtonRemoveFromMyPortfolio.setObjectName(_fromUtf8("toolButtonRemoveFromMyPortfolio"))
        self.verticalLayout_5.addWidget(self.toolButtonRemoveFromMyPortfolio)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.groupBox_2 = QtGui.QGroupBox(StructurePortefeuille)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetStructure = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetStructure.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidgetStructure.setMaximumSize(QtCore.QSize(555215, 16777215))
        self.tableWidgetStructure.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetStructure.setFont(font)
        self.tableWidgetStructure.setMidLineWidth(0)
        self.tableWidgetStructure.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetStructure.setDragDropOverwriteMode(False)
        self.tableWidgetStructure.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidgetStructure.setAlternatingRowColors(True)
        self.tableWidgetStructure.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetStructure.setShowGrid(False)
        self.tableWidgetStructure.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetStructure.setRowCount(0)
        self.tableWidgetStructure.setObjectName(_fromUtf8("tableWidgetStructure"))
        self.tableWidgetStructure.setColumnCount(3)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetStructure.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetStructure.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetStructure.setHorizontalHeaderItem(2, item)
        self.tableWidgetStructure.horizontalHeader().setVisible(True)
        self.tableWidgetStructure.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetStructure.verticalHeader().setVisible(True)
        self.tableWidgetStructure.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetStructure.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetStructure.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidgetStructure)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(StructurePortefeuille)
        QtCore.QMetaObject.connectSlotsByName(StructurePortefeuille)

    def retranslateUi(self, StructurePortefeuille):
        StructurePortefeuille.setWindowTitle(_translate("StructurePortefeuille", "Gérer structure portefeuille", None))
        self.sLectionnerLePortefeuilleModifierLabel.setText(_translate("StructurePortefeuille", "Sélectionner un portefeuille :", None))
        self.groupBox_2.setTitle(_translate("StructurePortefeuille", "Structure Portefeuille", None))
        item = self.tableWidgetStructure.horizontalHeaderItem(0)
        item.setText(_translate("StructurePortefeuille", "ISIN", None))
        item = self.tableWidgetStructure.horizontalHeaderItem(1)
        item.setText(_translate("StructurePortefeuille", "Nom", None))
        item = self.tableWidgetStructure.horizontalHeaderItem(2)
        item.setText(_translate("StructurePortefeuille", "Quantité", None))

